[default.probe]
# usb_vid = "1337"
# usb_pid = "1337"
# serial = "12345678"
protocol = "Swd"
# speed = 1337

[default.general]
chip = "stm32f446re"
chip_descriptions = []
# "OFF", "ERROR", "WARN", "INFO", "DEBUG", "TRACE"
log_level = "WARN"
connect_under_reset = false

[default.flashing]
enabled = true
restore_unwritten_bytes = false
do_chip_erase = false
# flash_layout_output_path = "out.svg"

[default.reset]
enabled = true
halt_afterwards = false

[default.rtt]
enabled = true
channels = [
    # { up = 0, down = 0, name = "name", format = "String" },

    # How to enable Defmt formatting (https://github.com/knurling-rs/defmt)
    # (formats on host, not on microcontroller)?
    # microcontroller setup: https://github.com/knurling-rs/app-template
    # { up = 0, name = "defmt_name", format = "Defmt" },
]
timeout = 3000
show_timestamps = true
log_enabled = false
log_path = "./logs"

[default.gdb]
enabled = false
gdb_connection_string = "127.0.0.1:1337"
